# Generated by Django 3.1 on 2022-01-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220120_0915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ADAMSpoken',
        ),
    ]
