# Generated by Django 3.1 on 2022-01-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_delete_adamspoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='guarantee_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty_description',
        ),
    ]
