# Generated by Django 3.1 on 2022-01-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20220120_1058'),
        ('market', '0006_auto_20220121_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_archive',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='scheduling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.scheduling'),
        ),
    ]
