# Generated by Django 3.1 on 2022-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20220121_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
