# Generated by Django 3.1 on 2022-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_order_is_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location',
        ),
    ]
