# Generated by Django 3.1 on 2022-01-21 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
