# Generated by Django 3.1 on 2022-01-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='qr_number',
        ),
    ]
