# Generated by Django 3.1 on 2022-05-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_category_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
