# Generated by Django 3.1 on 2022-01-20 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True)),
                ('calling_code', models.CharField(max_length=10)),
                ('flag_code', models.CharField(max_length=25, null=True, unique=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('is_capital', models.BooleanField(default=False)),
                ('time_zone', models.CharField(max_length=25, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.country')),
            ],
        ),
    ]
