# Generated by Django 3.1 on 2022-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20220120_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AddField(
            model_name='scheduling',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
