# Generated by Django 3.1 on 2022-05-06 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20220120_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='deliver_end_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
