# Generated by Django 3.1 on 2022-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_scheduling_deliver_end_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
