# Generated by Django 3.1 on 2022-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_location_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
