# Generated by Django 3.1 on 2022-05-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_state_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='deliver_date_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
